DEFAULT_INPUT_DIRECTORY = "_raw_modules"
DEFAULT_OUTPUT_FILE = "Data.json"
DEFAULT_BACKUP_DIRECTORY = "backup"

DEFAULT_TEST_INPUT_DIRECTORY = "_raw_modules"
DEFAULT_TEST_OUTPUT_FILE = "Data.json"
DEFAULT_TEST_BACKUP_DIRECTORY = "backup"